apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: assettrack
  labels:
    app: api-service
    linkerd.io/inject: enabled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: api-service
      containers:
      - name: api-service
        image: "192.168.0.70/assettrack/api-service:v1.0.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PROCESSOR_SERVICE_URL
          value: "http://processor-service:8000"
        - name: COLLECTOR_SERVICE_URL
          value: "http://collector-service:8000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1000

