apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: assettrack
  labels:
    app: api-service
spec:
  selector:
    app: api-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

