apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusRule
metadata:
  name: processor-db-critical
  namespace: monitoring
spec:
  groups:
  - name: processor.db.alerts
    rules:
    - alert: ProcessorDBCritical
      expr: |
        sum by (pod) (
          rate({namespace="assettrack", app="processor"} |= "CRITICAL: Cannot connect to database"[1m])
        ) > 5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Processor database connection failures"
        description: "More than 5 critical DB connection failures in 1 minute"


