apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: assettrack
  labels:
    app: processor
    linkerd.io/inject: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
        linkerd.io/inject: enabled
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
      containers:
      - name: processor
        image: "192.168.0.70/assettrack/processor:v1.0.0"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
        envFrom:
        - configMapRef:
            name: processor-config
        - secretRef:
            name: processor-secrets
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: processor
  namespace: assettrack
  labels:
    app: processor
spec:
  selector:
    app: processor
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000

