apiVersion: v1
kind: Secret
metadata:
  name: processor-secrets
  namespace: assettrack
type: Opaque
stringData:
  DB_USER: "assetuser"
  DB_PASSWORD: "assetpass"
  MQ_USER: "guest"
  MQ_PASSWORD: "guest"

