apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: assettrack
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432


