pipeline {
  agent any
  environment {
    IMAGE = '192.168.0.70/assettrack/processor:v1.0.0'
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Build') {
      steps {
        dir('aether-apps/app/processor-service') {
          sh 'docker build -t ${IMAGE} .'
        }
      }
    }
    stage('Push') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'harbor-creds', usernameVariable: 'HUSER', passwordVariable: 'HPASS')]) {
          sh 'echo $HPASS | docker login 192.168.0.70 -u $HUSER --password-stdin'
          sh 'docker push ${IMAGE}'
        }
      }
    }
  }
}

