apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-ui
  namespace: assettrack
  labels:
    app: webapp-ui
    linkerd.io/inject: enabled
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-ui
  template:
    metadata:
      labels:
        app: webapp-ui
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: webapp-ui
      containers:
      - name: webapp-ui
        image: "192.168.0.70/assettrack/webapp-ui:v1.0.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 101

