apiVersion: v1
kind: Service
metadata:
  name: webapp-ui
  namespace: assettrack
  labels:
    app: webapp-ui
spec:
  selector:
    app: webapp-ui
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP

